services:
  pg-db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./pg_data:/var/lib/postgresql/data:rw"
    ports:
      - "15432:5432"
    networks:
      - pg-dataengineering-network
  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "./pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8080:80"
    networks:
      - pg-dataengineering-network
networks:
  pg-dataengineering-network:
    name: pg-dataengineering-network